---
title: "Hdda2"
output: html_document
---

```{r setup, include=FALSE}
#library("rbiom")
library("biomformat")
library("phyloseq")
library("microbiome")
library("vegan")
library("gplots")
```

```{r}
biom <- read_biom("datasets/221_otu_table.biom")
summary(biom)
show(biom)
```


```{r}
fecal_samples = as(biom_data(biom), "matrix")
## taxonomic rank: 
# species -genus -family-class- phylum 
bacteria_taxa = observation_metadata(biom)

bacteria_taxa$taxonomy2 <- gsub("\\[|\\]", "", bacteria_taxa$taxonomy2)
bacteria_taxa$taxonomy3 <- gsub("\\[|\\]", "", bacteria_taxa$taxonomy3)
bacteria_taxa$taxonomy4 <- gsub("\\[|\\]", "", bacteria_taxa$taxonomy4)
bacteria_taxa$taxonomy5 <- gsub("\\[|\\]", "", bacteria_taxa$taxonomy5)
bacteria_taxa$taxonomy6 <- gsub("\\[|\\]", "", bacteria_taxa$taxonomy6)
```


```{r}
tax2 <- bacteria_taxa[,c("taxonomy1","taxonomy2")]
tax2["id"] <- rownames(tax2)
tax2["merge"] <- tidyr::unite(tax2[,-ncol(tax2)],"merge_type",sep = ",")

tax3 <- bacteria_taxa[,c("taxonomy1","taxonomy2", "taxonomy3")]
tax3["id"] <- rownames(tax3)
tax3["merge"] <- tidyr::unite(tax3[,-ncol(tax3)],"merge_type",sep = ",")

tax4 <- subset(bacteria_taxa[,c(1:4)], taxonomy4 != "o__")
tax4["id"] <- rownames(tax4)
tax4["merge"] <- tidyr::unite(tax4[,-ncol(tax4)],"merge_type",sep = ",")

tax5 <- subset(bacteria_taxa[,c(1:5)], taxonomy5 != "f__")
tax5["id"] <- rownames(tax5)
tax5["merge"] <- tidyr::unite(tax5[,-ncol(tax5)],"merge_type",sep = ",")

tax6 <- subset(bacteria_taxa[,c(1:6)], taxonomy6 != "g__")
tax6["id"] <- rownames(tax6)
tax6["merge"] <- tidyr::unite(tax6[,-ncol(tax6)],"merge_type",sep = ",")
```

```{r}
tax2[,c("taxonomy1","taxonomy2")] <- list(NULL)
tax3[,c("taxonomy1","taxonomy2","taxonomy3")] <- list(NULL)
tax4[,c("taxonomy1","taxonomy2","taxonomy3","taxonomy4")] <- list(NULL)
tax5[,c("taxonomy1","taxonomy2","taxonomy3","taxonomy4","taxonomy5")] <- list(NULL)
tax6[,c("taxonomy1","taxonomy2","taxonomy3","taxonomy4","taxonomy5","taxonomy6")] <- list(NULL)
```


```{r}
df_fecal <- as.data.frame(fecal_samples)
df_fecal$id <- rownames(df_fecal)
```


```{r}
library(dplyr)
prepare_data <- function(tax2){
  fec_tax2 <- as.data.frame(merge(df_fecal,tax2,by="id", sort = F))
  fec_tax2$id <- NULL
  fec_tax2 <- fec_tax2 %>% group_by(merge) %>% summarize_all(sum) 
  fec_tax2 <- as.data.frame(t(fec_tax2))
  colnames(fec_tax2) <- as.character(unlist(fec_tax2[1,]))
  fec_tax2 <- fec_tax2[-1,]
  return(fec_tax2)
}
```

```{r}
final_tax2 <- as.data.frame(prepare_data(tax2))
final_tax3 <- as.data.frame(prepare_data(tax3))
final_tax4 <- as.data.frame(prepare_data(tax4))
final_tax5 <- as.data.frame(prepare_data(tax5))
final_tax6 <- as.data.frame(prepare_data(tax6))
final <- cbind(final_tax2, final_tax3, final_tax4, final_tax5, final_tax6)
as.data.frame(t(final))
```


```{r}
final_tax6_ab <- as.data.frame(t(final_tax6))
final_tax6_ab <- as.data.frame(lapply(final_tax6_ab,function(x) as.numeric(as.character(x))))
final_tax6_ab <- as.data.frame(apply(final_tax6_ab,2, function(x){x/sum(x)}))
sum(final_tax6_ab[,1])
```

### CLUSTERING: 

```{r}
OTU <- otu_table(fecal_samples, taxa_are_rows = TRUE)
TAX <- tax_table(as.matrix(bacteria_taxa))
physeq <- phyloseq(OTU, TAX)
```

```{r}
physeq2 <- microbiome::aggregate_taxa(physeq, level = "taxonomy6")
```

```{r}
#df_fecal <- as.data.frame(lapply(df_fecal, as.numeric))
ph <- as.data.frame(otu_table(physeq2))
#dist_jsd <- philentropy::JSD(t(ph))

dist_jsd <- phyloseq::distance(physeq2, method = "jsd")


for (i in 2:20){
  clu <- cluster::pam(dist_jsd,i,diss = T, metric = "euclidean")
  print(clu$silinfo$avg.width)
}

heatmap(as.matrix(dist_jsd))

data_pca = as.data.frame(t(ph))
```


```{r}
nclusters=NULL
for (k in 2:20) { 
			clu <- cluster::pam(dist_jsd,k,diss = T, metric = "manhattan")
			nclusters[k-1]= clu$silinfo$avg.width
	}
plot(nclusters, type="h", xlab="k clusters", ylab="Average Silhouette width", main = "PAM clustering assessment")
```


```{r}
library("corrplot")
clu <- cluster::pam(dist_jsd,2,diss = T, metric = "euclidean") #get cluster 

mds <- cmdscale(dist_jsd,eig=TRUE, k=2) # k is the number of dim
variance_explained_mds = mds$GOF # cumulative percentage of variance explained by first 2 dimensions
x <- mds$points[,1]
y <- mds$points[,2]
plot (x,y,col=cluster_p, ylim = c(-0.8,0.8))

mds # view results

# plot solution
clu$medoids
medoid_cl1 = mds$points[rownames(mds$points) == clu$medoids[1],]
medoid_cl2 = mds$points[rownames(mds$points) == clu$medoids[2],]

data_mds = as.data.frame(mds$points)
colnames(data_mds) = c("x","y")

plot(x, y, main = "Multi Dimensional Scaling plot",col=cluster_p,pch=1)
points(medoid_cl1,pch=19)
points(medoid_cl2,pch=19)
```

```{r}
# differenze tra i cluster
data_pca$cluster = clu$clustering
cluster1 = data_pca[data_pca$cluster == 1,]
cluster2 = data_pca[data_pca$cluster == 2,]

cluster1_ab <- as.data.frame(t(apply(cluster1,1, function(x){x/sum(x)})))
cluster2_ab = as.data.frame(t(apply(cluster2,1, function(x){x/sum(x)})))

# si selezionano prevotella e bacteroides nei due cluster (da rivedere la scelta dei generi)
prevotella_cl1 = cluster1_ab$k__Bacteria_p__Bacteroidetes_c__Bacteroidia_o__Bacteroidales_f__Prevotellaceae_g__Prevotella
prevotella_cl2 = cluster2_ab$k__Bacteria_p__Bacteroidetes_c__Bacteroidia_o__Bacteroidales_f__Prevotellaceae_g__Prevotella
bacteroides_cl1 = cluster1_ab$g__Bacteroides
bacteroides_cl2 = cluster2_ab$g__Bacteroides

# boxplot sull'abundance di Bacteroides
boxplot(bacteroides_cl1,bacteroides_cl2, main= "Abundance Bacteroides in two clusters")

# Boxplot sull'abundance di Prevotella
boxplot(prevotella_cl1,prevotella_cl2, main = "Abundance Prevotella in two clusters")
```
#### Discretizzazione variabili dei nutrienti: 
```{r}
map_nutriens <- read.csv("datasets/46764_mapping_file.txt", sep = "\t")
numeric_cols <- unlist(lapply(map_nutriens, is.numeric))  

nut = map_nutriens[ , numeric_cols]

nut[,c("lib_reads_seqd","run_date","qiita_prep_id","age","anonymized_name","data_gen_ncc_database_ave",
                     "data_ncc_database_version","data_software_version_ave","day_of_intake","dri_life_stage_rda_cat",
                     "elevation","energy_kcal_ave","energy_kj_ave","host_subject_id","host_taxid","intake_amount",
                     "intake_reliability","latitude","longitude","perc_cal_from_protein_ave","perc_cal_from_pufa_ave",
                     "perc_cal_from_sfa_ave","polyunsatsat_fat_ratio_ave","qiita_study_id","taxon_id","visit_number")] <- list(NULL)

nutriens = cbind(map_nutriens$X.SampleID,nut)
names(nutriens)[1] = "id"
nutriens = nutriens[vapply(nutriens, function(x) length(unique(x)) > 1, logical(1L))]
to_levels <- gtools::quantcut(nutriens$aspartic_acid_g_ave,3,labels = c("low", "medium","high"))

library(gtools)
                   
to_quantile <- function(x){
    to_cut <- quantcut(x,3,labels = c("low", "medium","high"))
    try(to_cut <- quantcut(x,2,labels = c("very_low", "medium")), silent = TRUE)
    

  return (to_cut)
}    
#(quantile(x)[[1]][1] == 0) & (quantile(x)[[2]][1] == 0) & (quantile(x)[[3]][1] == 0) &
myFunc <- function(x)
{
  if (quantile(x)[[4]][1] == 0){
    to_cut = ifelse(x == 0, "assente", "presente")
  }
  else if (quantile(x)[[3]][1] != 0){
    to_cut = ifelse(x == 0, "assente", quantcut(x[x!=0],3, labels = c("low","medium","high")))
  }
  else {
    to_cut = ifelse(x == 0, "assente","presente")
  }
  return (to_cut)
}


nutriens2 <- nutriens
#nutriens2 <- nutriens2[,-c(51,52)]
#nutriens2<- nutriens2[,-116] 

for(i in 2:ncol(nutriens2)){
  app <- myFunc(nutriens2[,i])                                 
  nutriens2[,i] <- app
}

nutriens2[nutriens2 == 3] <- "high"
nutriens2[nutriens2 == 2] <- "medium"
nutriens2[nutriens2 == 1] <- "low"

quantile(nutriens$alcohol_g_ave)
``` 



```{r}
# merge nutriens dataset with data_pca dataset

standardize = function(col){
  col <- (col - mean(col)) / sd(col)
  return (col)
}
standardized_nutriens = as.data.frame(apply(nutriens[,-1],2,standardize))
standardized_nutriens$id = nutriens[,1]

data_pca$id = rownames(data_pca)
subject_clusters = data_pca[,c("id","cluster")]

nutriens_with_clusters = merge(subject_clusters,standardized_nutriens,by="id")
nutriens_cl1 = nutriens_with_clusters[nutriens_with_clusters$cluster==1,]
nutriens_cl2 = nutriens_with_clusters[nutriens_with_clusters$cluster==2,]

# verify nutrients - enterotype association

strength_nutrients_enterotype1_association = as.matrix(colMeans(nutriens_cl1[,-1]))
strength_nutrients_enterotype2_association = as.matrix(colMeans(nutriens_cl2[,-1]))
associations =cbind(strength_nutrients_enterotype1_association,strength_nutrients_enterotype2_association)

heatmap(associations[2:100,])


library(tidyr)
ass_df <- as.data.frame(associations)
ass_df$Nutrients <- rownames(ass_df)
ass_df <- ass_df[-1,]
rownames(ass_df) <- c(1:152)
prepo <- function(ass_df, n = 1, clu = "1"){
      ass_clu1 <-  ass_df[,c(n,3)]
      ass_clu1$cluster <- clu
      colnames(ass_clu1)[1] <- "Value"
      return (ass_clu1) 
}
  
ass_clu1 <- prepo(ass_df, n = 1, clu = "1")
ass_clu2 <- prepo(ass_df, n = 2, clu = "2")

ass_clu <- rbind(ass_clu1,ass_clu2)

library(ggplot2)

ggplot(data = ass_clu,
       aes(x = cluster, y = Nutrients, fill = Value)) + 
    geom_raster()  +
    xlab("Cluster") + 
    scale_fill_distiller(palette = "RdYlBu") +
    theme(axis.text.y = element_text(size = 6, angle = 0)) + #element_blank() (#axis.text.x = element_text(),
    ggtitle("ggplot heatmap")

```

```{r}
library("phyloseq")
#fecal_samples <- apply(fecal_samples,2,function(x){x/sum(x)})
#OTU <- otu_table(fecal_samples, taxa_are_rows = TRUE)
#TAX <- tax_table(as.matrix(bacteria_taxa))
#physeq <- phyloseq(OTU, TAX)
#plot_bar(physeq, fill = "taxonomy6")


#plot_bar(physeq2, fill = "taxonomy6")
```

```{r}
library("ape")
#random_tree = rtree(3393, rooted=TRUE, tip.label=taxa_names(physeq))
#plot(random_tree,show.tip.label = T)
```



```{r}
library(splitstackshape)

final_for_nutriens = as.data.frame(t(final))
final_for_nutriens$id = rownames(final_for_nutriens)
# calcolo abbondanza di final_for_nutriens
bacteria_taxa

taxa_for_nutriens = as.data.frame(final_for_nutriens[,"id"])
colnames(taxa_for_nutriens) = "taxonomy"

taxonomy = cSplit(taxa_for_nutriens, "taxonomy", sep=",")

taxonomy = as.data.frame(lapply(taxonomy, as.character),stringsAsFactors=FALSE)

taxonomy$taxonomy_3[is.na(taxonomy$taxonomy_3)] = "c__"
taxonomy$taxonomy_4[is.na(taxonomy$taxonomy_4)] = "o__"
taxonomy$taxonomy_5[is.na(taxonomy$taxonomy_5)] = "f__"
taxonomy$taxonomy_6[is.na(taxonomy$taxonomy_6)] = "g__"
rownames(taxonomy) = taxa_for_nutriens[,1]


taxa_nutrients = final_for_nutriens[,-ncol(final_for_nutriens)]
taxa_nutrients = as.data.frame(lapply(taxa_nutrients, function(x) as.numeric(as.character(x))))
rownames(taxa_nutrients) = final_for_nutriens$id


taxa_nutrients_ab <- as.data.frame(apply(taxa_nutrients,2,function(x){x/sum(x)}))
rownames(taxa_nutrients_ab) = final_for_nutriens[,"id"]

OTU <- otu_table(taxa_nutrients_ab, taxa_are_rows = TRUE)
TAX <- tax_table(as.matrix(taxonomy))
physeq <- phyloseq(OTU, TAX)
random_tree = rtree(198, rooted=TRUE, tip.label=taxa_names(physeq))
plot(random_tree,show.tip.label = F)

```


```{r}
phy_tax = merge_phyloseq(physeq, random_tree)
pro <- as.data.frame(otu_table(phy_tax))
plot_tree(phy_tax)
```


```{r}
distanza <- UniFrac(phy_tax, weighted=F, normalized=TRUE, parallel=TRUE, fast=TRUE)

get_id <- rownames(as.data.frame(t(otu_table(phy_tax))))
get_id <- gsub("X","", get_id)
# Match nutriens id with taxa id samples 
nut_true <- nutriens[match(get_id, nutriens2$id),]
```

```{r}
lista <- c()

for (i in 2:ncol(nut_true)){
  permanova <- vegan::adonis(distanza ~ nut_true[,i], data = nut_true,permutations=300, method = "bray")
  #print(permanova)
  if (unlist(permanova)$`aov.tab.Pr(>F)1` >= 0){
    lista = append(lista, unlist(permanova)$`aov.tab.Pr(>F)1`)
  }
}
``` 

```{r}
library(brainwaver)
pvalue.thresh <-compute.FDR(lista,q = .25)
```


```{r}

length(lista[lista <= 0.25])
FDR <- p.adjust(lista, method="BH")

length(FDR[FDR <= 0.25])
```



